-- Seed some sample news articles
insert into public.news (title, slug, excerpt, content, cover_image, category, published, published_at) values
('The Rise of Techno in Berlin: A New Era', 'rise-of-techno-berlin', 'Exploring how Berlin became the epicenter of modern techno culture', 'Berlin has long been recognized as the techno capital of the world. From the legendary Berghain to the countless underground venues scattered across the city, the German capital continues to push the boundaries of electronic music...', '/placeholder.svg?height=400&width=800', 'feature', true, now() - interval '2 days'),
('Interview: Charlotte de Witte on Her Latest Album', 'interview-charlotte-de-witte', 'The Belgian DJ discusses her creative process and upcoming projects', 'We sat down with Charlotte de Witte to discuss her evolution as an artist and what fans can expect from her upcoming releases. Her dedication to the craft and innovative approach to production continues to inspire...', '/placeholder.svg?height=400&width=800', 'interview', true, now() - interval '5 days'),
('Techno Festival Guide 2025: Must-Visit Events', 'techno-festival-guide-2025', 'Your complete guide to the most anticipated techno festivals this year', 'From Awakenings to Time Warp, 2025 promises to be an incredible year for techno festivals. We have compiled a comprehensive guide to help you plan your festival calendar and ensure you do not miss the biggest events...', '/placeholder.svg?height=400&width=800', 'feature', true, now() - interval '1 day');

-- Seed some sample events
insert into public.events (title, slug, description, venue, city, country, event_date, cover_image, ticket_url, lineup, price_from, price_to) values
('Berghain: Friday Night', 'berghain-friday-night', 'Classic Berghain experience with international lineup', 'Berghain', 'Berlin', 'Germany', now() + interval '3 days', '/placeholder.svg?height=400&width=800', 'https://berghain.berlin', '["Ben Klock", "Marcel Dettmann", "Answer Code Request"]'::jsonb, 20, 20),
('Awakenings Festival 2025', 'awakenings-festival-2025', 'The biggest techno festival returns to Amsterdam', 'Spaarnwoude', 'Amsterdam', 'Netherlands', now() + interval '90 days', '/placeholder.svg?height=400&width=800', 'https://awakenings.com', '["Adam Beyer", "Charlotte de Witte", "Nina Kraviz", "Amelie Lens"]'::jsonb, 89, 129),
('Tresor Berlin: Techno Tuesday', 'tresor-techno-tuesday', 'Underground techno in the legendary Tresor vault', 'Tresor', 'Berlin', 'Germany', now() + interval '1 day', '/placeholder.svg?height=400&width=800', 'https://tresorberlin.com', '["Dax J", "I Hate Models", "Kobosil"]'::jsonb, 15, 15);

-- Seed some sample DJ releases
insert into public.dj_releases (title, artist, label, release_date, cover_art, description, tracklist, spotify_url, beatport_url, genre) values
('Dark Matter EP', 'Amelie Lens', 'LENSKE', current_date - interval '7 days', '/placeholder.svg?height=400&width=400', 'A powerful 4-track EP showcasing Amelie signature dark and driving sound', '["Dark Matter", "Event Horizon", "Singularity", "Cosmic Drift"]'::jsonb, 'https://spotify.com', 'https://beatport.com', array['Techno', 'Peak Time']),
('Monolith', 'Ben Klock', 'Klockworks', current_date - interval '14 days', '/placeholder.svg?height=400&width=400', 'Ben Klock delivers another masterclass in hypnotic techno', '["Monolith", "Axis", "Subzero"]'::jsonb, 'https://spotify.com', 'https://beatport.com', array['Techno', 'Minimal']),
('Rave Tools Vol. 1', 'I Hate Models', 'Perc Trax', current_date - interval '3 days', '/placeholder.svg?height=400&width=400', 'Hard-hitting techno tools for the peak time dance floor', '["Tool 1", "Tool 2", "Tool 3", "Tool 4"]'::jsonb, 'https://spotify.com', 'https://beatport.com', array['Techno', 'Hard Techno']);

-- Seed some sample videos
insert into public.videos (title, description, youtube_url, thumbnail_url, artist, event_name, video_date, duration, category) values
('Ben Klock - Boiler Room Berlin', 'Legendary set from Berghain resident Ben Klock at Boiler Room', 'https://youtube.com/watch?v=example1', '/placeholder.svg?height=360&width=640', 'Ben Klock', 'Boiler Room Berlin', current_date - interval '30 days', 7200, 'set'),
('Charlotte de Witte - Tomorrowland 2024', 'Main stage performance at Tomorrowland', 'https://youtube.com/watch?v=example2', '/placeholder.svg?height=360&width=640', 'Charlotte de Witte', 'Tomorrowland 2024', current_date - interval '120 days', 3600, 'set'),
('The Story of Detroit Techno - Documentary', 'Exploring the origins of techno music in Detroit', 'https://youtube.com/watch?v=example3', '/placeholder.svg?height=360&width=640', 'Various Artists', 'Detroit Techno Documentary', current_date - interval '60 days', 5400, 'documentary');
