-- Script SQL para crear eventos de prueba
-- Ejecutar este script en el SQL Editor de Supabase

INSERT INTO events (title, slug, description, event_date, venue, city, country, event_type, lineup, image_url, ticket_url, featured, header_featured, status, language)
VALUES
  (
    'Techno Underground Madrid',
    'techno-underground-madrid',
    '<p>Una noche épica de techno underground en el corazón de Madrid. Los mejores DJs del panorama nacional e internacional se reúnen para una sesión inolvidable.</p>',
    (NOW() + INTERVAL '7 days' + INTERVAL '23 hours')::TIMESTAMPTZ,
    'Fabrik',
    'Madrid',
    'España',
    'club',
    ARRAY['Charlotte de Witte', 'Amelie Lens', 'Reinier Zonneveld', 'Nina Kraviz'],
    'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1920&q=80',
    'https://example.com/tickets',
    true,
    true,
    'PUBLISHED',
    'es'
  ),
  (
    'Barcelona Techno Festival',
    'barcelona-techno-festival',
    '<p>El festival de techno más importante de Barcelona. Tres días de música electrónica con los artistas más destacados del momento.</p>',
    (NOW() + INTERVAL '14 days' + INTERVAL '20 hours')::TIMESTAMPTZ,
    'Poble Espanyol',
    'Barcelona',
    'España',
    'promoter_festival',
    ARRAY['Adam Beyer', 'Cirez D', 'Drumcode', 'Maceo Plex'],
    'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1920&q=80',
    'https://example.com/tickets',
    true,
    true,
    'PUBLISHED',
    'es'
  ),
  (
    'Valencia Techno Night',
    'valencia-techno-night',
    '<p>Una noche intensa de techno en Valencia. Sonidos oscuros y profundos que te transportarán a otro nivel.</p>',
    (NOW() + INTERVAL '10 days' + INTERVAL '22 hours')::TIMESTAMPTZ,
    'La Fábrica de Hielo',
    'Valencia',
    'España',
    'club',
    ARRAY['Dax J', 'Kobosil', 'I Hate Models', '999999999'],
    'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=1920&q=80',
    'https://example.com/tickets',
    false,
    false,
    'PUBLISHED',
    'es'
  ),
  (
    'Bilbao Industrial Techno',
    'bilbao-industrial-techno',
    '<p>Techno industrial y hard techno en Bilbao. Una experiencia sonora brutal para los amantes del techno más duro.</p>',
    (NOW() + INTERVAL '21 days' + INTERVAL '23 hours' + INTERVAL '30 minutes')::TIMESTAMPTZ,
    'Kafe Antzokia',
    'Bilbao',
    'España',
    'club',
    ARRAY['Paula Temple', 'Anetha', 'VTSS', 'Shlømo'],
    'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=1920&q=80',
    'https://example.com/tickets',
    true,
    false,
    'PUBLISHED',
    'es'
  ),
  (
    'Sevilla Deep Techno',
    'sevilla-deep-techno',
    '<p>Techno profundo y atmosférico en Sevilla. Una noche para perderse en los sonidos más profundos del techno.</p>',
    (NOW() + INTERVAL '18 days' + INTERVAL '22 hours' + INTERVAL '30 minutes')::TIMESTAMPTZ,
    'Sala Custom',
    'Sevilla',
    'España',
    'club',
    ARRAY['Stephan Bodzin', 'Oliver Huntemann', 'Extrawelt', 'Dominik Eulberg'],
    'https://images.unsplash.com/photo-1501281668745-f7f63ba5f4ba?w=1920&q=80',
    'https://example.com/tickets',
    false,
    false,
    'PUBLISHED',
    'es'
  ),
  (
    'Málaga Beach Techno',
    'malaga-beach-techno',
    '<p>Techno en la playa de Málaga. Una experiencia única combinando música electrónica y ambiente playero.</p>',
    (NOW() + INTERVAL '25 days' + INTERVAL '18 hours')::TIMESTAMPTZ,
    'Playa de la Misericordia',
    'Málaga',
    'España',
    'promoter_festival',
    ARRAY['Solomun', 'Dixon', 'Tale Of Us', 'Afterlife'],
    'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1920&q=80',
    'https://example.com/tickets',
    true,
    true,
    'PUBLISHED',
    'es'
  ),
  (
    'Zaragoza Minimal Techno',
    'zaragoza-minimal-techno',
    '<p>Minimal techno en Zaragoza. Sonidos limpios y precisos para una noche de baile perfecta.</p>',
    (NOW() + INTERVAL '12 days' + INTERVAL '23 hours')::TIMESTAMPTZ,
    'Sala Oasis',
    'Zaragoza',
    'España',
    'club',
    ARRAY['Ricardo Villalobos', 'Sven Väth', 'Richie Hawtin', 'Dubfire'],
    'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1920&q=80',
    'https://example.com/tickets',
    false,
    false,
    'PUBLISHED',
    'es'
  ),
  (
    'Murcia Techno Underground',
    'murcia-techno-underground',
    '<p>La escena underground de Murcia se reúne para una noche de techno puro y duro.</p>',
    (NOW() + INTERVAL '16 days' + INTERVAL '23 hours' + INTERVAL '30 minutes')::TIMESTAMPTZ,
    'Sala REM',
    'Murcia',
    'España',
    'club',
    ARRAY['Regal', 'D.Dan', 'Blawan', 'Karenn'],
    'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=1920&q=80',
    'https://example.com/tickets',
    false,
    false,
    'PUBLISHED',
    'es'
  )
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  event_date = EXCLUDED.event_date,
  venue = EXCLUDED.venue,
  city = EXCLUDED.city,
  country = EXCLUDED.country,
  event_type = EXCLUDED.event_type,
  lineup = EXCLUDED.lineup,
  image_url = EXCLUDED.image_url,
  ticket_url = EXCLUDED.ticket_url,
  featured = EXCLUDED.featured,
  header_featured = EXCLUDED.header_featured,
  status = EXCLUDED.status,
  updated_at = NOW();

