CREATE TABLE eventos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nombre TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    descripcion TEXT,
    fecha_inicio TIMESTAMPTZ NOT NULL,
    fecha_fin TIMESTAMPTZ NOT NULL,
    venue_nombre TEXT NOT NULL,
    venue_direccion TEXT,
    ciudad TEXT NOT NULL,
    pais TEXT,
    promotor_id UUID,
    artistas TEXT[],
    lineup JSONB,
    estado TEXT DEFAULT 'borrador' CHECK (estado IN ('borrador',
    'aprobado',
    'publicado',
    'cancelado',
    'archivado')),
    flyer_url TEXT,
    imagenes TEXT[],
    url_entradas TEXT,
    precio JSONB,
    capacidad INTEGER,
    edad_minima INTEGER,
    tipo_evento TEXT,
    ra_event_id TEXT,
    ra_synced BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);