CREATE TABLE lanzamientos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    titulo TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    artistas UUID[],
    sello_id UUID,
    tipo_lanzamiento TEXT CHECK (tipo_lanzamiento IN ('single',
    'ep',
    'album',
    'remix',
    'compilacion')),
    fecha_lanzamiento DATE NOT NULL,
    genero TEXT,
    subgenero TEXT,
    bpm INTEGER,
    key_musical TEXT,
    tracklist JSONB,
    creditos JSONB,
    artwork_url TEXT,
    enlaces_tiendas JSONB,
    enlaces_streaming JSONB,
    estado TEXT DEFAULT 'borrador' CHECK (estado IN ('borrador',
    'pendiente_derechos',
    'aprobado',
    'publicado')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);